"""Per-question evidence (which real page answers which part) and the position of each question in the course."""

# Course order = the order the material was taught. Book sources sit outside the sequence.
STAGES = [
    ("L1", "Lecture 1", "ระบบฝังตัวและสถาปัตยกรรม 8051", "รู้ว่าชิปมีอะไรข้างใน: CPU, ROM, RAM, Timer, Serial, คริสตัลและ PC", "ฐานของ clock 12 MHz และ Program Counter"),
    ("L2", "Lecture 2", "ขาของ 8051 และ PSW", "หน้าที่ขา 40 ขา และแฟล็กใน PSW เช่น Parity", "ฐานของบิต parity ที่เห็นใน Serial 9 บิต"),
    ("L3", "Lecture 3", "หน่วยความจำ, Stack และ SFR", "RAM 128 ไบต์, Stack ที่ SP ชี้ และตาราง SFR แอดเดรส TCON, TMOD, SCON, IE, IP", "ทุกรีจิสเตอร์ที่ข้อสอบถามอยู่ในตารางนี้"),
    ("L4", "Lecture 4", "Assembler และชุดคำสั่ง", "MOV, SETB, CLR, JB, JNB, DJNZ, SJMP, CALL, RET, RETI", "ภาษาที่ใช้เขียนโค้ดตอบข้อ 9 และข้อ 21"),
    ("L5", "Lecture 5", "Timer และ Counter", "TCON, TMOD, 4 โหมด, สูตร Count = FFFFH - Value + 1", "ข้อ 1 ถึง 9 อยู่ที่นี่ทั้งหมด"),
    ("L6", "Lecture 6", "Serial, Interrupt และ Power saving", "SCON, SBUF, 5 interrupt, IE, IP, Vector table, ISR", "ข้อ 10 ถึง 18 อยู่ที่นี่เป็นหลัก"),
    ("LAB3", "Lab 3", "ฮาร์ดแวร์ DC motor และไฟจราจร", "H-bridge, PWM, ไดรเวอร์ L293D และ Hardware diagram ของไฟคนข้าม", "ข้อ 19, 20 และรูป Hardware ของข้อ 21"),
    ("LSM", "Lab 5", "State machine", "เขียน state chart เป็นโค้ด Traffic 1, 2, 3 พร้อม delay 10 µs", "ข้อ 21 เกือบเหมือนตัวอย่าง Traffic 1"),
]
BOOKS = ("MZ16", "MZ11", "UCB3")

# question -> [(slide key, why this page matters for this question)]
QEVID = {
    1: [
        ("L5-02", "ภาพคำตอบหลัก: ซ้าย Timer รับ Clock จาก Osc. ภายในชิป ขวา Counter รับ External Clock จากขา T0 และ T1"),
        ("L5-05", "นิยามที่อาจารย์เขียนเอง: clock ภายใน = Timer, clock ภายนอกที่ T0/T1 = Counter และตั้งด้วยบิต T/C ของ TMOD"),
        ("L5-07", "สรุปสองบรรทัดกลางสไลด์: T0 และ T1 นับ clock ภายใน = Timer, นับ clock ภายนอก = Counter ควบคุมด้วย TCON และ TMOD"),
        ("L5-12", "วงจรสวิตช์ C/T: 0 = Timer (Fosc/12), 1 = Counter (ขา T0/T1) ดูเส้นทางของ clock ในชิปจริง"),
        ("L5-14", "ขา 14 (T0) = P3.4 และขา 15 (T1) = P3.5 คือทางเข้าของ clock ภายนอก"),
        ("L1-19", "ต้นกำเนิดของ clock ภายใน คือคริสตัลที่ขา XTAL1 และ XTAL2"),
    ],
    2: [
        ("L5-03", "คำตอบตรงตัว: 2 Timer, 16 บิต, up counter และแตกเป็น TH0-TL0, TH1-TL1"),
        ("L5-16", "โหมด 1: TLX 8 บิต ต่อกับ THX 8 บิต เป็นตัวนับ 16 บิตนับขึ้นทีละ 1"),
        ("L3-12", "ตาราง SFR ให้แอดเดรสจริง: TL0 = 8AH, TL1 = 8BH, TH0 = 8CH, TH1 = 8DH"),
        ("L1-18", "ในแผนผังชิปมี Timer 0 และ Timer 1 อยู่ข้าง CPU พร้อมช่อง Counter Input"),
    ],
    3: [
        ("L5-04", "บรรทัดที่ 3 และ 4: ถึง FFFFH แล้วกลิ้งกลับ 0000H และเกิด Timer Overflow interrupt"),
        ("L5-06", "แผนภาพลูกศร: กลิ้ง FFFFH → 0000H ทำให้ TF = 1 แล้วล้าง TF ก่อนเข้า ISR และกลับด้วย RETI"),
        ("L5-09", "TF1 และ TF0 คือ Timer Overflow Flag: เซตเป็น 1 เมื่อ overflow และล้างเมื่อ CPU เข้า ISR"),
        ("L5-16", "โหมด 1: TFX เป็น 1 เมื่อ 16 บิตกลิ้งจาก FFFFH ไป 0000H"),
    ],
    4: [
        ("L5-04", "สูตรที่ต้องใช้: Count = FFFFH - Value + 1 พร้อมตัวอย่างนับ 9 ได้ FFF7H วิธีเดียวกับ 100 µs"),
        ("L5-16", "โหมด 1 นับได้สูงสุด 65,536 counts ใช้ตรวจว่า 100 อยู่ในช่วงที่ทำได้"),
        ("L5-20", "ตัวอย่างของอาจารย์ 20 µs → FFECH ทำตามขั้นตอนเดียวกันทุกบรรทัด"),
        ("L5-21", "ตัวอย่างเสริมท้ายข้อ 4 ในสมุด: 0.5 ms = 500 = 1F4H → FE0CH (TH0 = FEH, TL0 = 0CH)"),
        ("L1-19", "คริสตัล 12 MHz ที่ทำให้ 1 count = 12 / 12 MHz = 1 µs"),
        ("L4-23", "รูปแบบคำสั่ง MOV แบบ immediate ที่ใช้โหลด TH0 และ TL0"),
    ],
    5: [
        ("L5-09", "TR1 และ TR0 = Timer Run Control Bit: 1 = Start Counting, 0 = Halts Timer (TF ใต้กรอบเดียวกันคือ Overflow Flag)"),
        ("L5-13", "บรรทัดแรก: To have running counter, TR bit of TCON register must be 1"),
        ("L5-12", "ในวงจรมีเกต AND ที่รับ TR0/TR1 ปิด TR เมื่อไร ตัวนับไม่เดิน"),
        ("L5-20", "MOV TCON, #00010000B คือตั้ง TR0 = 1 เริ่มนับ และ MOV TCON, #00H คือหยุด"),
    ],
    6: [
        ("L5-10", "นิยามตรง: IT = 1 ให้ INT ทำงานที่ -ve edge trigger ดูเส้นตกจาก Logic 1 เป็น Logic 0 ในรูปวาดมือ"),
        ("L5-09", "IT1 และ IT0 เป็นบิต 2 และบิต 0 ของ TCON (อยู่ข้าง IE1 และ IE0)"),
        ("L6-12", "ตัวอย่างจริง: setb TCON.0 (IT0 = 1) เพื่อให้ INT0 ทำงานที่ขอบขาลง"),
    ],
    7: [
        ("L5-11", "ตาราง M1 M0 → Timer Mode 0, 1, 2, 3 อยู่ล่างสุดของสไลด์"),
        ("L5-15", "Mode 0 = 13 บิต (TLX 5 บิต + THX 8 บิต) สูงสุด 8192"),
        ("L5-16", "Mode 1 = 16 บิต สูงสุด 65,536"),
        ("L5-17", "Mode 2 = 8 บิต auto reload: THX โหลดกลับเข้า TLX เมื่อล้น"),
        ("L5-19", "Mode 3 = แยก Timer 0 เป็นสอง Timer 8 บิต (TL0 ให้ TF0, TH0 ให้ TF1)"),
    ],
    8: [
        ("L5-11", "บิต C/T: SET 1 = Acts as Counter {External Frequency on T1 & T0} (สำหรับ Timer 0 คือ TMOD.2)"),
        ("L5-12", "สวิตช์ C/T = 1 ต่อขา T0 หรือ T1 เข้าตัวนับ"),
        ("L5-14", "ขา 14 คือ T0 (P3.4) ต้องต่อสัญญาณที่จะนับเข้าขานี้"),
        ("L5-13", "ต้องเซต TR ให้ตัวนับเดิน และ GATE = 0 เพื่อไม่ให้ขึ้นกับขา INTX"),
    ],
    9: [
        ("LSM-05", "โค้ด delay 10 µs ของอาจารย์: TH0 = FFH, TL0 = F6H แต่ละบรรทัดคือหนึ่งกล่องใน Flowchart"),
        ("L5-04", "สูตร FFFFH - Value + 1 ใช้กับ 10 (0AH) ได้ FFF6H"),
        ("L5-20", "แม่แบบลำดับ ตั้ง TMOD → โหลด TH/TL → เริ่ม Timer → รอ TF0 → หยุด"),
        ("L5-16", "โหมด 1 ที่ใช้ (TMOD = 01H)"),
        ("L4-31", "JNB TCON.5, Wait คือกล่องตัดสินใจ 'TF0 = 1 ?' ใน Flowchart"),
    ],
    10: [
        ("L6-02", "แผนภาพ SBUF สองชุด: ส่งออกทาง TxD (P3.1) และรับเข้าทาง RxD (P3.0) ข้อความขวาบอกให้ตั้งค่าด้วย SCON"),
        ("L6-03", "การเขียน SBUF ตอนส่ง (MOV SBUF, A) และอ่านตอนรับ (MOV A, SBUF) พร้อมล้าง Ti และ Ri"),
        ("L6-04", "บิตของ SCON: SM0 SM1 SM2 REN TB8 RB8 TI RI และตารางโหมด"),
        ("L6-07", "บิต TI และ RI ใน SCON เป็น 1 เมื่อ SBUF ส่งหรือรับครบ 8 บิต และโปรแกรมเมอร์ต้องล้างเอง"),
        ("L3-12", "แอดเดรส SCON = 98H และ SBUF = 99H"),
        ("L1-18", "Serial Port (TXD, RXD) เป็นส่วนหนึ่งของชิปในแผนผังโครงสร้าง"),
        ("MZ11-428", "ตำราอธิบายทำไมต้องใช้คริสตัล 11.0592 MHz กับ baud rate (เนื้อหาเสริม)"),
    ],
    11: [
        ("L6-04", "ตารางโหมด: Mode 0 = Shift Register (Fosc/12) กับ Mode 1 = 8 bit UART (Variable)"),
        ("L6-05", "รูปเฟรม: Mode 0 มีแต่ D0-D7 ส่วน Mode 1 มี Start 0 + D0-D7 + Stop 1"),
    ],
    12: [
        ("L6-04", "Mode 2 และ 3 คือ 9 bit UART ต่างจาก Mode 1 ที่ 8 bit UART"),
        ("L6-05", "รูปเฟรม Mode 2 และ 3 มีบิต P เพิ่มระหว่าง D7 กับ Stop bit"),
        ("L6-06", "TB8 และ RB8 คือบิตที่ 9 ที่โปรแกรมเมอร์กำหนดเป็น parity"),
        ("L2-11", "บิต P ใน PSW: ฮาร์ดแวร์คำนวณ parity ของ A (คี่ P = 1, คู่ P = 0) นำมาใส่ TB8 ได้"),
        ("L2-06", "ตำแหน่งบิต P ที่ D0 ของ PSW"),
    ],
    13: [
        ("L6-08", "รายชื่อ 5 interrupt: INT0, INT1, TF0, TF1 และ Serial (RI หรือ TI)"),
        ("L6-09", "ตารางชื่อ ลำดับ และ Vector Address ของทั้ง 5 ตัว"),
        ("L6-13", "ตาราง Vector อีกแบบที่มีคอลัมน์ Pin และ Flag Clearing"),
    ],
    14: [
        ("L6-08", "สไลด์ตอบตรง: Hardware 2 ตัว, Timer overflow ภายใน 2 ตัว และ Serial ภายใน 1 ตัว รวมเป็น 3 ประเภท"),
        ("L6-13", "ตารางที่แยกให้เห็นว่า INT0 และ INT1 มีขา (12, 13) ส่วน Timer และ Serial เป็นภายใน (ไม่มีขา)"),
    ],
    15: [
        ("L1-23", "PC 16 บิต: ตัวอย่าง PC = 0x009 ส่งแอดเดรสเพื่อดึงคำสั่ง 54H (คำตอบของข้อ 15)"),
        ("L1-20", "Address bus 16 บิต คือเหตุผลที่ PC กว้าง 16 บิต"),
        ("L1-22", "เทียบกับ SP 8 บิตที่ชี้ Stack (อย่าสับสนกับ PC)"),
        ("L3-09", "Stack ใช้เก็บ return address ของ ISR และซับรูทีน"),
        ("L6-09", "เข้า ISR: PUSH PC ก่อน จบด้วย POP PC และ RETI"),
        ("L4-26", "CALL เก็บ PC ลง Stack แล้ว RET คืนค่า"),
        ("L4-28", "RET กับ RETI ต่างกันที่ RETI ตั้ง EA = 1 ด้วย"),
    ],
    16: [
        ("L6-09", "ตาราง Priority และ Vector Address: 0003H, 000BH, 0013H, 001BH, 0023H"),
        ("L6-13", "ตาราง Vector มีแอดเดรส Reset 0000 และคอลัมน์ Flag Clearing"),
        ("L6-12", "โค้ดตัวอย่าง org 0003H → AJMP count แสดงการวางคำสั่งที่ vector"),
        ("L5-09", "ข้อความใน TCON ก็ระบุ ISR address ของ Timer 0 (000BH), Timer 1 (001BH), INT0 (0003H), INT1 (0013H)"),
    ],
    17: [
        ("L6-10", "IE = Interrupt Enable Register: EA, ET2, ES, ET1, EX1, ET0, EX0"),
        ("L6-11", "IP = Interrupt Priority Register: PT2, PS, PT1, PX1, PT0, PX0"),
        ("L3-12", "แอดเดรส IE = A8H และ IP = B8H"),
    ],
    18: [
        ("L6-09", "ตารางลำดับ priority: INT0 = 1, TF0 = 2, INT1 = 3, TF1 = 4, Serial = 5 (ลำดับ 2 = TF0)"),
        ("L6-11", "IP register ที่ใช้เปลี่ยน priority ได้ (PT0 = Priority Timer 0)"),
        ("L6-13", "ตาราง Vector ยืนยัน TF0 อยู่ที่ 000BH"),
    ],
    19: [
        ("LAB3-06", "สไลด์ของอาจารย์: คุมความเร็วด้วยการเปลี่ยนปริมาณกำลังไฟ ด้วยเทคนิค PWM ดูคลื่น 25%, 50%, 75%, 100%"),
        ("LAB3-07", "L293D: ขา Enable 1,2 รับ PWM จาก 8051 เพื่อคุมความเร็ว"),
        ("MZ16-565", "ตำราอธิบาย PWM: พัลส์กว้างขึ้น ความเร็วสูงขึ้น (แอมพลิจูดคงที่ duty cycle เปลี่ยน)"),
        ("MZ16-566", "รูป 16-9 เทียบ duty cycle 25%, 50%, 75%, 100%"),
        ("LAB3-03", "เหตุผลที่ต้องคุมกำลัง: โหลดเพิ่ม RPM ลด เว้นแต่เพิ่มแรงดันหรือกระแส"),
    ],
    20: [
        ("LAB3-02", "บรรทัดที่ 3: By reversing supply of motor change its direction (คำตอบตรงตัว)"),
        ("LAB3-04", "มอเตอร์สองชุดสลับขั้วแบตเตอรี่: Clockwise และ Anticlockwise"),
        ("LAB3-05", "H-bridge สามแบบ: not running, clockwise และ counter clockwise"),
        ("LAB3-07", "L293D: Input 1 และ Input 2 จาก 8051 คุมทิศทาง"),
        ("MZ16-559", "ตำรา: reversing the polarity ทำให้มอเตอร์หมุนกลับทิศ"),
        ("MZ16-560", "รูป 16-2: H-bridge สี่สวิตช์ (เปิดหมด = motor not running)"),
        ("MZ16-561", "รูป 16-3 และ 16-4: ปิด SW1+SW4 = ทิศหนึ่ง ปิด SW2+SW3 = ทิศตรงข้าม"),
        ("MZ16-562", "Table 16-2 ตารางสวิตช์ และรูป 16-5 Invalid (ลัดวงจร)"),
        ("MZ16-563", "รูป 16-6 ต่อ H-bridge ผ่าน L298 กับ AVR (ตำราใช้ L298 ส่วนสไลด์ใช้ L293D)"),
    ],
    21: [
        ("LSM-02", "State chart กับ Hardware ของ Traffic 1 ตรงกับรูปในข้อสอบ: Ready --push--> Go, Go --timer--> Ready, Go --push--> Go"),
        ("LAB3-10", "ฉากทางม้าลายและปุ่มกดของโจทย์"),
        ("LAB3-11", "Hardware Diagram: P1.1 ไฟคนแดง, P1.0 ไฟคนเขียว, P2.0 ปุ่มกด"),
        ("LSM-03", "เฉลยโค้ด ReadyState ของอาจารย์ (ส่วนที่ข้อ 21 ให้เขียน)"),
        ("LSM-04", "โค้ด GoState: เปิดไฟเขียว รอ 10 รอบ แล้ว jB p2.0 หรือกลับ Ready"),
        ("LSM-05", "ซับรูทีน delay 10 µs ที่ GoState เรียกใช้ (FFF6H)"),
        ("L4-21", "SETB และ CLR ที่ใช้เปิดปิดบิตพอร์ต P1.1, P1.0"),
        ("L4-31", "JB P2.0, GoState อ่านปุ่ม (กด = 1 กระโดด)"),
        ("L4-29", "SJMP ReadyState วนกลับไม่มีเงื่อนไข"),
        ("L4-30", "DJNZ R1, timer วนลูปนับ 10 รอบ"),
        ("L4-26", "call delay / RET เรียกและกลับจากซับรูทีน"),
        ("L4-23", "MOV R0, #01H และ MOV R1, #10 (immediate)"),
        ("UCB3-67", "ตำรา: นิยามของ state machine และ FSM (จำนวน state จำกัด)"),
        ("UCB3-68", "ตำรา: สัญลักษณ์ state, transition และป้าย guard / action"),
        ("UCB3-78", "ตำรา: Moore กับ Mealy เอาต์พุตไฟผูกกับ state จึงเป็น Moore"),
    ],
}

# question -> (main stage, section index in that stage), prerequisites, what builds on it
POS = {
    1: (("L5", 1), [("L1", "คริสตัลคือต้นกำเนิด clock (Lecture 1 หน้า 19)"), ("L3", "TMOD เป็น SFR ที่ใช้เลือก Timer/Counter")], "ข้อ 4 ใช้ clock ภายในคำนวณเวลา และข้อ 8 ตั้งเป็น Counter"),
    2: (("L5", 1), [("L1", "8051 เป็นซีพียู 8 บิต จึงต้องแบ่งตัวนับ 16 บิตเป็นสองไบต์"), ("L3", "SFR คือรีจิสเตอร์ 8 บิตที่แอดเดรส 80H ถึง FFH")], "ข้อ 4 ต้องแยกค่านับเป็น TH และ TL"),
    3: (("L5", 2), [("L5", "ข้อ 2: ตัวนับ 16 บิตนับขึ้น (จึงมีจุดล้น)")], "ข้อ 13 และ 16: overflow เป็น interrupt ที่ vector 000BH และ 001BH"),
    4: (("L5", 2), [("L1", "คริสตัล 12 MHz → 1 machine cycle = 1 µs"), ("L4", "คำสั่ง MOV ที่ใช้โหลด TH0, TL0"), ("L5", "ข้อ 2 และ 3: ตัวนับขึ้นและจุดล้น")], "ข้อ 9 (delay 10 µs), Lab 5 ซับรูทีน delay และข้อ 21"),
    5: (("L5", 3), [("L5", "ข้อ 3: TF ใน TCON เป็นแฟล็ก ส่วน TR เป็นตัวสั่งเดิน")], "ข้อ 9 ต้องเซต TR0 เพื่อเริ่มนับ"),
    6: (("L5", 3), [("L5", "ข้อ 5: TCON เป็นรีจิสเตอร์ควบคุม IT อยู่ในนั้นด้วย")], "Lecture 6 หัวข้อ ISR programming ใช้ setb TCON.0 ตั้งขอบขาลงของ INT0"),
    7: (("L5", 3), [("L5", "ข้อ 2: ตัวนับ 16 บิต (Mode 1) เป็นโหมดที่รู้จักแล้ว")], "ข้อ 4 และ 9 ใช้ Mode 1 (TMOD = 01H)"),
    8: (("L5", 4), [("L5", "ข้อ 1: Timer กับ Counter ต่างกันที่ clock"), ("L3", "ขา P3.4 (T0) เป็นพอร์ต 3 ตามตาราง SFR")], "จบเรื่อง Timer/Counter ต่อด้วย Serial ใน Lecture 6"),
    9: (("L5", 6), [("L4", "JNB, SJMP, RET ที่ใช้ในโค้ด"), ("L5", "ข้อ 4, 5 และ 7: สูตรค่านับ, TR และ Mode 1")], "ข้อ 21 เรียกซับรูทีนนี้เป็น delay 10 µs"),
    10: (("L6", 1), [("L3", "SCON และ SBUF เป็น SFR (98H, 99H)"), ("L1", "Serial Port (TXD, RXD) อยู่ในชิป")], "ข้อ 11 และ 12 ต่างกันที่โหมดของ SCON"),
    11: (("L6", 1), [("L6", "ข้อ 10: SCON ตั้งโหมด")], "ข้อ 12 เทียบต่อกับ 9 bit UART"),
    12: (("L6", 1), [("L2", "บิต P (parity) ใน PSW"), ("L6", "ข้อ 11: เฟรม 8 bit UART")], "จบส่วน Serial ต่อด้วย Interrupt"),
    13: (("L6", 2), [("L5", "TF0 และ TF1 มาจาก Timer (ข้อ 3)"), ("L6", "RI และ TI มาจาก Serial (ข้อ 10)")], "ข้อ 14 ถึง 18 ขยายความ interrupt ทั้งห้า"),
    14: (("L6", 2), [("L6", "ข้อ 13: รู้ทั้ง 5 ตัวแล้วจึงจัดกลุ่มได้")], "ข้อ 17 และ 18 คือการเปิดและจัดลำดับของกลุ่มเหล่านี้"),
    15: (("L1", 5), [("L1", "Address bus 16 บิต"), ("L3", "Stack เก็บ return address")], "Lecture 6: เข้า ISR ต้อง PUSH PC และ RETI จะ POP PC (ข้อ 16)"),
    16: (("L6", 4), [("L6", "ข้อ 13: รายชื่อ interrupt"), ("L4", "AJMP และ RETI ที่ใช้ที่ vector")], "ข้อ 17 และ 18: เปิดและจัดลำดับความสำคัญ"),
    17: (("L6", 3), [("L3", "IE และ IP เป็น SFR (A8H, B8H)"), ("L6", "ข้อ 13: ต้องรู้ 5 interrupt ก่อนเปิด")], "ข้อ 18 ใช้ IP เปลี่ยนลำดับ"),
    18: (("L6", 3), [("L6", "ข้อ 16 และ 17: ตาราง Vector และ IE/IP")], "จบ Interrupt ต่อด้วยฮาร์ดแวร์ใน Lab 3"),
    19: (("LAB3", 3), [("L5", "Timer สร้างพัลส์ความกว้างต่าง ๆ ได้ (ข้อ 4)"), ("LAB3", "DC motor พื้นฐาน (หน้า 2 และ 3)")], "ข้อ 20 ใช้ไดรเวอร์ L293D ตัวเดียวกันคุมทิศทาง"),
    20: (("LAB3", 2), [("LAB3", "DC motor พื้นฐาน (หน้า 2)"), ("LAB3", "ข้อ 19: ไดรเวอร์ L293D")], "ข้อ 21 ใช้ฮาร์ดแวร์ Lab 3 ชุดถัดไป (ไฟจราจร)"),
    21: (("LSM", 1), [("L4", "MOV, SETB, CLR, JB, DJNZ, SJMP, CALL"), ("L5", "ข้อ 4 และ 9: delay ด้วย Timer"), ("LAB3", "Hardware Diagram P1.1, P1.0, P2.0")], "ข้อสุดท้ายรวมทุกบท: Lab 5 Traffic 2 และ 3 คือรูปแบบต่อยอดที่ควรฝึก"),
}
